Imports System.Net.Mail
Imports System.Configuration
Imports System.Windows.Forms

Public Class SendEMail
    Dim Toaddress As New List(Of String)()


    Public Sub SendMail(ByVal StrMsg As String, ByVal Bodynumber As String)

        Toaddress.Clear()
        Toaddress.Add(System.Configuration.ConfigurationManager.AppSettings("ToEmails").ToString())


        Dim strFromMailID As String = [String].Empty
        Dim strSmtp As String = [String].Empty
        Dim strbody As String = String.Empty
        Dim port As Integer = 0
        Dim MyMessage As New MailMessage()
        strFromMailID = System.Configuration.ConfigurationManager.AppSettings("FromEmail").ToString()
        strSmtp = System.Configuration.ConfigurationManager.AppSettings("SMTP").ToString()
        port = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings("PortNO").ToString())

        Dim SendFrom As New MailAddress(strFromMailID)
        MyMessage.From = SendFrom
        MyMessage.[To].Clear()
        MyMessage.CC.Clear()
        MyMessage.Bcc.Clear()
        MyMessage.Body = ""
        MyMessage.Subject = System.Configuration.ConfigurationManager.AppSettings("Subject").ToString() & Bodynumber & " SERVER :" & My.Computer.Name

        strbody = "<table border=0 cellspacing=0 cellpadding=0> " & _
         "<tr><td>Dear All," & _
         "</td></tr>" & _
       "<tr><td><br/> BC Data Error Occurred . Error Code :" & StrMsg & "<br/><br/>" & _
 "________ DO NOT REPLY TO THIS MAIL . THIS IS AUTOGENERATED E-MAIL ________ </td></tr>"

        For Each ToAddr As String In Toaddress
            MyMessage.[To].Add(ToAddr)
        Next

        MyMessage.Body = strbody
        MyMessage.IsBodyHtml = True

        Dim smtp As New SmtpClient()
        smtp.UseDefaultCredentials = True
        smtp.Host = strSmtp
        smtp.Port = port
        smtp.Send(MyMessage)


    End Sub

    Public Sub SendStatusMail(ByVal StrMsg As String, ByVal Bodynumber As String)

        Toaddress.Clear()
        Toaddress.Add(System.Configuration.ConfigurationManager.AppSettings("StatusEmails").ToString())


        Dim strFromMailID As String = [String].Empty
        Dim strSmtp As String = [String].Empty
        Dim strbody As String = String.Empty
        Dim port As Integer = 0
        Dim MyMessage As New MailMessage()
        strFromMailID = System.Configuration.ConfigurationManager.AppSettings("FromEmail").ToString()
        strSmtp = System.Configuration.ConfigurationManager.AppSettings("SMTP").ToString()
        port = Convert.ToInt32(System.Configuration.ConfigurationManager.AppSettings("PortNO").ToString())

        Dim SendFrom As New MailAddress(strFromMailID)
        MyMessage.From = SendFrom
        MyMessage.[To].Clear()
        MyMessage.CC.Clear()
        MyMessage.Bcc.Clear()
        MyMessage.Body = ""
        MyMessage.Subject = System.Configuration.ConfigurationManager.AppSettings("Subject").ToString() & Bodynumber & " SERVER :" & My.Computer.Name

        Dim St As String = System.Configuration.ConfigurationManager.AppSettings("StatusMail").ToString() & StrMsg

        For Each ToAddr As String In Toaddress
            MyMessage.[To].Add(ToAddr)
        Next

        strbody = "<table border=0 cellspacing=0 cellpadding=0> " & _
         "<tr><td>Dear All," & _
         "</td></tr>" & _
       "<tr><td><br/>" & St & " " & Date.Now & "<br/><br/>" & _
        " ________ DO NOT REPLY TO THIS MAIL . THIS IS AUTOGENERATED E-MAIL ________ </td></tr>"


        MyMessage.Body = strbody
        MyMessage.IsBodyHtml = True

        Dim smtp As New SmtpClient()
        smtp.UseDefaultCredentials = True
        smtp.Host = strSmtp
        smtp.Port = port
        smtp.Send(MyMessage)


    End Sub



End Class
